# Generated by Django 5.2.8 on 2025-11-26 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='addres_line_1',
            new_name='address_line_1',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='addres_line_2',
            new_name='address_line_2',
        ),
    ]
